# Shell variables
# Generated by 'wal'
wallpaper="/home/mamat/Pictures/Wallpapers/hyprchan.png"

# Special
background='#101010'
foreground='#c3c3c3'
cursor='#c3c3c3'

# Colors
color0='#101010'
color1='#566BAE'
color2='#49A4C1'
color3='#C6B3BE'
color4='#AAE5D4'
color5='#FCD4CC'
color6='#CFCEF1'
color7='#c3c3c3'
color8='#6c5959'
color9='#566BAE'
color10='#49A4C1'
color11='#C6B3BE'
color12='#AAE5D4'
color13='#FCD4CC'
color14='#CFCEF1'
color15='#c3c3c3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
