[colors.primary]
background = "#101010"
foreground = "#c3c3c3"

[colors.cursor]
text = "#101010"
cursor = "#c3c3c3"

[colors.vi_mode_cursor]
text = "#101010"
cursor = "#c3c3c3"

[colors.search.matches]
foreground = "#101010"
background = "#c3c3c3"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#6c5959"
background = "#c3c3c3"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#101010"
red = "#566BAE"
green = "#49A4C1"
yellow = "#C6B3BE"
blue = "#AAE5D4"
magenta = "#FCD4CC"
cyan = "#CFCEF1"
white = "#c3c3c3"

[colors.bright]
black = "#6c5959"
red = "#566BAE"
green = "#49A4C1"
yellow = "#C6B3BE"
blue = "#AAE5D4"
magenta = "#FCD4CC"
cyan = "#CFCEF1"
white = "#c3c3c3"

[colors.dim]
black = "#c3c3c3"
red = "#566BAE"
green = "#FCD4CC"
yellow = "#C6B3BE"
blue = "#AAE5D4"
magenta = "#49A4C1"
cyan = "#CFCEF1"
white = "#6c5959"

