--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/mamat/Pictures/hyprchan.png"

-- Special
background="#101010"
foreground="#e0eee8"
cursor="#e0eee8"

-- Colors
color0="#101010"
color1="#566BAE"
color2="#49A4C1"
color3="#C6B3BE"
color4="#AAE5D4"
color5="#FCD4CC"
color6="#CFCEF1"
color7="#e0eee8"
color8="#9ca6a2"
color9="#566BAE"
color10="#49A4C1"
color11="#C6B3BE"
color12="#AAE5D4"
color13="#FCD4CC"
color14="#CFCEF1"
color15="#e0eee8"
